import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { supabase } from '../lib/supabase';

type Topic = { id: string; name: string; description: string | null };
type TopicScripture = { topic_id: string; relevance_rank: number | null; verse: { id: string; verse_number: number; text: string; chapter: { id: string; chapter_number: number; book: { canonical_key: string; name: string } }; version: { abbreviation: string; name: string } } };

export function TopicSearch() {
  const navigate = useNavigate(); const [topics,setTopics]=useState<Topic[]>([]); const [query,setQuery]=useState(''); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{supabase.from('topics').select('id,name,description').order('name').then(({data,error:e})=>{if(e)setError(e.message);setTopics(data??[]);setLoading(false);});},[]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?topics.filter(t=>`${t.name} ${t.description??''}`.toLowerCase().includes(q)):topics;},[topics,query]);
  return <main className="topic-page"><section className="topic-hero card"><div><span className="eyebrow">TOPIC STUDY</span><h1>Find Scripture by topic.</h1><p>Search verified study topics and discover the Scriptures connected to each one.</p></div><input className="catalog-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search topics…" aria-label="Search topics"/></section>{loading&&<section className="card catalog-message">Loading topics…</section>}{error&&<section className="card catalog-message"><h2>Unable to load topics</h2><p>{error}</p></section>}{!loading&&!error&&filtered.length===0&&<section className="card empty-state"><strong>{topics.length===0?'No topics have been published yet.':'No topics match your search.'}</strong><p>{topics.length===0?'Topic mappings will appear here as verified Scripture study data is added.':'Try another topic name or keyword.'}</p></section>}{filtered.length>0&&<section className="topic-grid">{filtered.map(t=><button key={t.id} className="topic-card card" onClick={()=>navigate(`/explore/topic/${t.id}`)}><span className="study-icon">⌕</span><div><strong>{t.name}</strong><p>{t.description??'Explore Scriptures connected to this topic.'}</p></div></button>)}</section>}</main>;
}

export function TopicStudy(){
  const {topicId}=useParams(); const navigate=useNavigate(); const [topic,setTopic]=useState<Topic|null>(null); const [items,setItems]=useState<TopicScripture[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(!topicId)return;let cancelled=false;(async()=>{setLoading(true);const [{data:t,error:te},{data:s,error:se}]=await Promise.all([supabase.from('topics').select('id,name,description').eq('id',topicId).maybeSingle(),supabase.from('topic_scriptures').select('topic_id,relevance_rank,bible_verses(id,verse_number,text,bible_chapters(id,chapter_number,bible_books(canonical_key,name)),bible_versions(name,abbreviation))').eq('topic_id',topicId).order('relevance_rank',{ascending:true,nullsFirst:false})]);if(cancelled)return;if(te||se)setError(te?.message??se?.message??'Unable to load topic.');setTopic(t??null);const normalized=((s??[]) as any[]).map(row=>{const v=row.bible_verses,c=Array.isArray(v?.bible_chapters)?v.bible_chapters[0]:v?.bible_chapters,b=Array.isArray(c?.bible_books)?c.bible_books[0]:c?.bible_books,ver=Array.isArray(v?.bible_versions)?v.bible_versions[0]:v?.bible_versions;if(!v||!c||!b||!ver)return null;return {topic_id:row.topic_id,relevance_rank:row.relevance_rank,verse:{id:v.id,verse_number:v.verse_number,text:v.text,chapter:{id:c.id,chapter_number:c.chapter_number,book:{canonical_key:b.canonical_key,name:b.name}},version:{name:ver.name,abbreviation:ver.abbreviation}}};}).filter(Boolean);setItems(normalized);setLoading(false);})();return()=>{cancelled=true}},[topicId]);
  if(loading)return <main className="topic-study page-card"><p>Loading topic study…</p></main>; if(error||!topic)return <main className="topic-study page-card"><h1>Topic study unavailable</h1><p>{error??'Topic not found.'}</p><button onClick={()=>navigate('/explore/topics')}>Back to topics</button></main>;
  return <main className="topic-study"><section className="topic-study-hero card"><button className="back-button" onClick={()=>navigate('/explore/topics')}>← Topics</button><span className="eyebrow">TOPIC STUDY</span><h1>{topic.name}</h1><p>{topic.description??'Explore the Scriptures connected to this topic.'}</p><span className="count-chip">{items.length} Scripture{items.length===1?'':'s'}</span></section>{items.length===0?<section className="card empty-state"><strong>No Scripture mappings yet.</strong><p>This topic exists, but no verified Scripture references have been connected yet.</p></section>:<section className="saved-list">{items.map(item=><article key={item.verse.id} className="bookmark-card"><div className="bookmark-main"><span className="label">{item.verse.version.abbreviation}</span><button className="reference-button" onClick={()=>navigate(`/bible/${item.verse.chapter.book.canonical_key}/${item.verse.chapter.chapter_number}`)}>{item.verse.chapter.book.name} {item.verse.chapter.chapter_number}:{item.verse.verse_number}</button><p>{item.verse.text}</p></div><div className="bookmark-actions"><button onClick={()=>navigate(`/bible/${item.verse.chapter.book.canonical_key}/${item.verse.chapter.chapter_number}`)}>Read chapter →</button></div></article>)}</section>}</main>;
}
